global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "cockroachdb.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - tasks.node-exporter
      type: A
      port: 9100

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - tasks.cadvisor
      type: A
      port: 8080

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter-01:9104', 'mysql-exporter-02:9104', 'mysql-exporter-03:9104', 'mysql-exporter-04:9104', 'mysql-exporter-05:9104']

  - job_name: 'cockroach'
    metrics_path: '/_status/vars'
    static_configs:
      - targets: ['cockroachdb-01:8080', 'cockroachdb-02:8080', 'cockroachdb-03:8080', 'cockroachdb-04:8080', 'cockroachdb-05:8080']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-exporter:9101']
